name: tag

on: workflow_dispatch

jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      with:
        fetch-depth: 0
    - name: Create tag
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
